version: "3"

services:

    heralding4:
        build: ./images/heralding_imm
        container_name: heralding4
        cap_add:
        - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
        - ./configurations/heralding:/home
        networks:
          my_network:
            ipv4_address: 172.28.0.2
        ports:
          - "2022:22"  # Port forwarding dalla porta 2022 dell'host alla porta 22 del container
          - "2021:21"  # Port forwarding dalla porta 2021 dell'host alla porta 21 del container
          - "2080:1080"  # Port forwarding dalla porta 2080 dell'host alla porta 1080 del container

    heralding3:
        build: ./images/heralding_imm
        container_name: heralding3
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/heralding:/home
        networks:
          my_network:
            ipv4_address: 172.28.0.3
        ports:
          - "3022:22"  # Port forwarding dalla porta 2022 dell'host alla porta 22 del container
          - "3021:21"  # Port forwarding dalla porta 3021 dell'host alla porta 21 del container
          - "3080:1080"  # Port forwarding dalla porta 23080 dell'host alla porta 1080 del container
          

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

