version: "3"

services:
    heralding2:
        build: ./images/heralding_imm
        container_name: heralding2
        cap_add:
        - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
        - ./configurations/heralding:/home
        networks:
          my_network:
            ipv4_address: 172.28.0.2
        ports:
          - "2022:22"  # Port forwarding dalla porta 2022 dell'host alla porta 22 del container

    heralding:
        build: ./images/heralding_imm
        container_name: heralding
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/heralding:/home
        networks:
          my_network:
            ipv4_address: 172.28.0.3
        ports:
          - "3022:22"  # Port forwarding dalla porta 2022 dell'host alla porta 22 del container

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

