version: "3"

services:
    int_host: 
        build: ./images/host_imm
        container_name: int_host
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/int_host:/home
    int_ssh_server:
        build: ./images/ssh_imm
        container_name: int_ssh_server
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/int_ssh_server:/home
    controller:
        build: ./images/ryu_imm
        container_name: controller
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/controller:/home
    heralding2:
        build: ./images/heralding_imm
        container_name: heralding2
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/heralding:/home
