version: "3"

services:
    int_host_ev: 
        build: ./images/host_imm
        container_name: int_host_ev
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/int_host:/home
    dmz_host_ev:
        build: ./images/host_imm
        container_name: ext_host_ev
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/ext_host:/home       
    dmz_service_ev:
        build: ./images/ssh_imm
        container_name: ssh_server_ev
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/ssh_server:/home
    int_ssh_server:
        build: ./images/ssh_imm
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/int_ssh_server:/home
        deploy:
          mode: replicated
          replicas: 30
    controller_ev:
        build: ./images/ryu_imm
        container_name: controller_ev
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/controller:/home
