version: "3"

services:

    evaluation3:
        build: ./images/heralding_imm
        container_name: evaluation3
        cap_add:
        - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
        - ./configurations/heralding:/home
        networks:
          my_network:
            ipv4_address: 172.28.0.25
        ports:
          - "6006:22"  
          - "6007:21" 
          - "6008:1080"

    evaluation2:
        build: ./images/heralding_imm
        container_name: evaluation2
        cap_add:
        - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
        - ./configurations/heralding:/home
        networks:
          my_network:
            ipv4_address: 172.28.0.22
        ports:
          - "6003:22"  
          - "6004:21" 
          - "6005:1080"

    evaluation1:
        build: ./images/heralding_imm
        container_name: evaluation1
        cap_add:
        - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
        - ./configurations/heralding:/home
        networks:
          my_network:
            ipv4_address: 172.28.0.21
        ports:
          - "6000:22"  
          - "6001:21" 
          - "6002:1080"

    test:
        build: ./images/heralding_imm
        container_name: test
        cap_add:
        - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
        - ./configurations/heralding:/home
        networks:
          my_network:
            ipv4_address: 172.28.0.20
        ports:
          - "5022:22"  
          - "5021:21" 
          - "5080:1080"
    heralding2:
        build: ./images/heralding_imm
        container_name: heralding2
        cap_add:
        - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
        - ./configurations/heralding:/home
        networks:
          my_network:
            ipv4_address: 172.28.0.2
        ports:
          - "2022:22"  # Port forwarding dalla porta 2022 dell'host alla porta 22 del container
          - "2021:21"  # Port forwarding dalla porta 2021 dell'host alla porta 21 del container
          - "2080:1080"  # Port forwarding dalla porta 2080 dell'host alla porta 1080 del container

    heralding:
        build: ./images/heralding_imm
        container_name: heralding
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/heralding:/home
        networks:
          my_network:
            ipv4_address: 172.28.0.3
        ports:
          - "3022:22"  # Port forwarding dalla porta 2022 dell'host alla porta 22 del container
          - "3021:21"  # Port forwarding dalla porta 3021 dell'host alla porta 21 del container
          - "3080:1080"  # Port forwarding dalla porta 23080 dell'host alla porta 1080 del container
          

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

