version: "3"

services:
    int_host_lan2: 
        build: ./images/host_imm
        container_name: int_host_lan2
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/int_host:/home
    controller_lan2:
        build: ./images/ryu_imm
        container_name: controller_lan2
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/controller:/home

